### ISSUE TITLE
Docs/demo updates for v2

### ISSUE THREAD

**Issue by davidrleonard** [PredixDev/px-app-nav#70]
The following concepts need to be explained:

* [x] The nav must be switched to collapsed mode on touch devices. The vertical nav does not support touch devices because it requires a hover state to be show. (#63)
* [x] In horizontal/collapsed (non-vertical) mode, the nav defaults to `position:relative` and `display:block`. It is up to the developer to set it to `position:fixed` or `position:absolute` to get it to stick to the top. Otherwise it won't stick to the stop and things will scroll over it. We need to explain that. The developer can also use our px-app-helpers nav wrapper. (#50)
* [x] Document how to select an item by reference and by using string by route (#46)
* [x] Document how collapse-at works (it is measuring the avail width, not the window width) and include instructions for using `iron-media-query` to collapse at a specific window width instead (#64)
* [x] We need a more complete HISTORY.md, with breaking API changes, for the refresh (#69)
* [x] We need a migration guide for people using the existing px-app-nav (#69)
  * [x] Migrate data
  * [x] Migrate routing behaviors (esp. in predix-webapp-starter)
* [x] The demo needs to be extended to show more complex nav configurations. (#67)
